spring:
  application:
    name: course-service

  datasource:
    url: jdbc:postgresql://localhost:5432/lms
    username: postgres
    password: anil@123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  web:
    resources:
      static-locations: classpath:/static/

server:
  port: 8080

jwt:
  secret: bXlfc2VjcmV0X2tleV9teV9zZWNyZXRfa2V5X3Byb2R1Y3Rpb25fdXNlX3N0cm9uZ2VyX2tleV8yNTZfYml0c19sb25n
  issuer: https://auth.nucleusteq.com

gateway:
  validation:
    enabled: false
  secret:
    header: X-Gateway-Secret
    value: your-super-secret-gateway-key-change-this-in-production
  signature:
    header: X-Gateway-Signature

direct:
  secret:
    header: X-Direct-Secret
    value: your-super-secret-direct-key-change-this-in-production
