spring.application.name=course-service
spring.datasource.url = jdbc:postgresql://localhost:5432/lms_db
spring.datasource.username = postgres
spring.datasource.password = root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
server.port = 8080
spring.web.resources.static-locations=classpath-:/static/

# JWT Configuration (should match API Gateway)(must be 256 bits for HS256 algorithm)
jwt.secret=my_secret_key_my_secret_key_my_secret_key_for_production_use_stronger_key_256_bits_long
jwt.issuer=https://auth.nucleusteq.com

# Gateway Security Configuration
gateway.validation.enabled=false
gateway.secret.header=X-Gateway-Secret
gateway.secret.value=your-super-secret-gateway-key-change-this-in-production

# Gateway signature validation (optional)
gateway.signature.header=X-Gateway-Signature

#Direct Access Security headers
direct.secret.header = X-Direct-Secret
direct.secret.value = your-super-secret-direct-key-change-this-in-production