spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/lms_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    out-of-order: false
    table: flyway_schema_history

server:
  port: 8081

logging:
  level:
    org.springframework.web: DEBUG

jwt:
  secret: bXlfc2VjcmV0X2tleV9teV9zZWNyZXRfa2V5X3Byb2R1Y3Rpb25fdXNlX3N0cm9uZ2VyX2tleV8yNTZfYml0c19sb25n
  issuer: https://auth.nucleusteq.com

gateway:
  validation:
    enabled: true
  secret:
    header: X-Gateway-Secret
    value: your-super-secret-gateway-key-change-this-in-production
  signature:
    header: X-Gateway-Signature

direct:
  secret:
    header: X-Direct-Secret
    value: your-super-secret-direct-key-change-this-in-production
